# yaml-language-server: $schema=https://json.schemastore.org/commitlintrc.json

extends: "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - - chore
      - feat
      - fix
