# editorconfig-checker-disable-next-line
# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

extends: markdownlint/style/prettier
